### ISSUE TITLE
crash LMMFPver45

### ISSUE THREAD

**Issue by FrixionCoffee** [FrixionCoffee/LittleSlimeGirl#1]
## system information
minecraft 1.12.2
forge 14.23.5.2854
LittleMaidReengaged_FirisPatch-9.2.1.fp.045
LMLibrary-1.0.5
littleMaidModel_LittleSlimeGirlPlusAddon-1.12.2

## happen bug
multi playing is crashed.

## バグ内容
上記環境マルチプレイ時にクラッシュする

**Comment by FrixionCoffee** [comment]
# bug case2
## バグ内容
上記環境シングルプレイ時もクラッシュする
---
# bug case3
## system information
minecraft 1.12.2
forge 14.23.5.2768
LittleMaidReengaged_FirisPatch-9.2.0.fp.044.jar
LMLibrary-1.0.3.jar
littleMaidModel_LittleSlimeGirlPlusAddon-1.12.2

<details>
  <summary>crashReport</summary>

  ```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LMLibCoreMod (LMLibrary-1.0.3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/31/20 8:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LMLibrary (lmlibrary)
Caused by: java.lang.NoClassDefFoundError: net/blacklab/lmr/entity/maidmodel/ModelRenderer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at firis.lmlib.common.loader.LMMultiModelHandler.loadHandler(LMMultiModelHandler.java:132)
	at firis.lmlib.common.loader.LMFileLoader.load(LMFileLoader.java:101)
	at firis.lmlib.LMLibrary.preInit(LMLibrary.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.blacklab.lmr.entity.maidmodel.ModelRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 454443304 bytes (433 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version      | Source                                              | Signature                                |
	|:----- |:----------------------- |:------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2       | minecraft.jar                                       | None                                     |
	| LCH   | mcp                     | 9.42         | minecraft.jar                                       | None                                     |
	| LCH   | FML                     | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                   | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | lmlibrary_coremod       | 1.0.0        | minecraft.jar                                       | None                                     |
	| LCH   | little_slime_girl_addon | 2019.2-1.3.1 | littleMaidModel_LittleSlimeGirlPlusAddon-1.12.2.jar | None                                     |
	| LCE   | lmlibrary               | 1.0.3        | LMLibrary-1.0.3.jar                                 | None                                     |
	| LC    | lmreengaged             | 9.2.0.fp.044 | LittleMaidReengaged_FirisPatch-9.2.0.fp.044.jar     | None                                     |

	Loaded coremods (and transformers): 
LMLibCoreMod (LMLibrary-1.0.3.jar)
  firis.lmlib.core.LMLibTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
  ```
</details>

**Comment by FrixionCoffee** [comment]
## 原因
アドオンなしも試したが、同様にクラッシュする。しかし他のモデルではクラッシュが見られないので、恐らくクラス構造に問題がある

## 変更
改修は困難なソースなので、時間はかかるが、一から作成する
現在のLMMFPではmodsフォルダ以外にマルチモデルを配置するようになっているので、アドオン機能は分離する必要がある

**Comment by FrixionCoffee** [comment]
v1.1で対応
